spring.application.name=catalogo

spring.datasource.url=jdbc:mysql://localhost:3306/vertDB
spring.datasource.username=root
spring.datasource.password=sk8ordie
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
