
cloudflare.r2.access-key=${CLOUDFLARE_R2_ACCESS_KEY}
cloudflare.r2.secret-key=${CLOUDFLARE_R2_SECRET_KEY}
cloudflare.r2.bucket=${CLOUDFLARE_R2_BUCKET}
cloudflare.r2.account-id=${CLOUDFLARE_R2_ACCOUNT_ID}
cloudflare.r2.public-url=${CLOUDFLARE_R2_PUBLIC_URL}