# Configuración JWT
jwt.private-key=romabar-super-segura
jwt.issuer=accesoriosvert.online
jwt.expiration-milis=1800000
jwt.refresh-expiration-minutes=10080
jwt.refresh-token-cookie-name=refresh_token
jwt.access-token-cookie-name=access_token
jwt.cookie-secure=true